Vagrant.configure("2") do |config|
	  
      #Define Number of RAM for each node
	  
	   config.vm.define "puppetE" do |puppetE|
		   #puppetE.vm.network :public_network, :public_network => "eth1"
		    puppetE.vm.box = "ubuntu/trusty64"
			
			#puppetE.vm.network "forwarded_port", 443, 8443
			
		    puppetE.vm.network :public_network, ip: "192.168.1.95"
			
		    puppetE.vm.provision :shell,path: "puppetEnterprise.sh"
			
			puppetE.vm.hostname = "master.local"
			
			puppetE.vm.provider :virtualbox do |v|
               v.customize ["modifyvm", :id, "--memory", 1024, "--vram", "13"]
		       v.name = "PuppetEnterprise(Master)"
		       v.gui  = true
		       v.memory = 4096
		       v.cpus = 1
	        end
	    end
		
		   # Provision Config for each of the nodes
       config.vm.define "agent1" do |agent1|
	   
           #agent1.vm.network :public_network, :public_network => "eth1"
		     agent1.vm.box = "ubuntu/trusty64"
			 	 agent1.vm.network :public_network, ip: "192.168.1.94"
             agent1.vm.provision :shell,path: "agent1.sh"	
		
			 agent1.vm.hostname = "agent1.local"
			 
			 agent1.vm.provider :virtualbox do |v|
                v.customize ["modifyvm", :id, "--memory", 1024, "--vram", "13"]
		        v.name = "PuppetEnterprise(Agent)"
		        v.gui  = true
		        v.memory = 4096
		        v.cpus = 1
	        end
	    end
		  
end