#dockerfile
FROM ubuntu:14.04

RUN sudo apt-get update
RUN sudo apt-get install -y git
RUN sudo apt-get install -y vagrant
RUN sudo apt-get install -y wget
#install virtual box
RUN sudo sh -c "echo 'deb http://download.virtualbox.org/virtualbox/debian '$(lsb_release -cs)' contrib non-free' > /etc/apt/sources.list.d/virtualbox.list" && wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add - && sudo apt-get update && sudo apt-get install -y virtualbox-4.3

WORKDIR /Documents/

#get our project
RUN git clone https://github.com/BilalMahmoodNet/puppetlegion.git

#go into the vagrant folder
WORKDIR /Documents/puppetlegion/vagrant/vagrant/

#run the project
RUN vagrant up
