FROM Ubuntu:14.04

RUN sudo apt-get update
RUN sudo apt-get install -y git
RUN sudo apt-get install -y vagrant

WORKDIR /Documents/

RUN git clone https://github.com/BilalMahmoodNet/puppetlegion.git

WORKDIR /Documents/puppetlegion/vagrant/vagrant/

RUN vagrant up
